export default {
  // general
  SET_COMPAREVIEW: "SET_COMPAREVIEW",

  // main map
  SET_ISLOADING: "SET_ISLOADING",
  SET_LONGITUDE: "SET_LONGITUDE",
  SET_LATITUDE: "SET_LATITUDE",
  SET_ZOOM: "SET_ZOOM",
  SET_MAXZOOM: "SET_MAXZOOM",
  SET_MINZOOM: "SET_MINZOOM",
  SET_BOUNDARY: "SET_BOUNDARY",

  SET_CELLSIZE: "SET_CELLSIZE",

  ADD_GRID_DATA: "ADD_GRID_DATA",
  CLEAR_GRID_DATA: "CLEAR_GRID_DATA",
  ADD_SELECTED_DATA: "ADD_SELECTED_DATA",
  REMOVE_SELECTED_DATA: "REMOVE_SELECTED_DATA",
  CLEAR_SELECTED_DATA: "CLEAR_SELECTED_DATA",
  SET_PANEL_DATA: "SET_PANEL_DATA",

  SET_TOOLTIP: "SET_TOOLTIP",
  SET_POPUP: "SET_POPUP",

  SET_TIMEFILTER: "SET_TIMEFILTER",
  SET_FEATURE_FILTER: "SET_FEATURE_FILTER",
  CLEAR_FEATURE_FILTER: "CLEAR_FEATURE_FILTER",

  // secondary map
  SET_ISLOADING_2: "SET_ISLOADING_2",
  SET_LONGITUDE_2: "SET_LONGITUDE_2",
  SET_LATITUDE_2: "SET_LATITUDE_2",
  SET_ZOOM_2: "SET_ZOOM_2",
  SET_MAXZOOM_2: "SET_MAXZOOM_2",
  SET_MINZOOM_2: "SET_MINZOOM_2",
  SET_BOUNDARY_2: "SET_BOUNDARY_2",

  SET_CELLSIZE_2: "SET_CELLSIZE_2",

  ADD_GRID_DATA_2: "ADD_GRID_DATA_2",
  CLEAR_GRID_DATA_2: "CLEAR_GRID_DATA_2",
  ADD_SELECTED_DATA_2: "ADD_SELECTED_DATA_2",
  REMOVE_SELECTED_DATA_2: "REMOVE_SELECTED_DATA_2",
  CLEAR_SELECTED_DATA_2: "CLEAR_SELECTED_DATA_2",
  SET_PANEL_DATA_2: "SET_PANEL_DATA_2",

  SET_TOOLTIP_2: "SET_TOOLTIP_2",
  SET_POPUP_2: "SET_POPUP_2",

  SET_TIMEFILTER_2: "SET_TIMEFILTER_2",
  SET_FEATURE_FILTER_2: "SET_FEATURE_FILTER_2",
  CLEAR_FEATURE_FILTER_2: "CLEAR_FEATURE_FILTER_2"
}